### ISSUE TITLE
On the selection of Technology

### ISSUE THREAD

**Issue by 0x00-qa** [masayuki038/truffle-arrow-language#1]
Is Graalvm better than Gandiva? How do you choose between these two technologies?

**Comment by masayuki038** [comment]
So far, I have not  compared these technologies. I'm implementing to allow to profile this guest language so that I can check the performance. 

https://github.com/masayuki038/truffle-arrow-language/commit/749ccdc0ce532a75102374c31aea8dcea13bfe08

And I hope to bring out the potential of GraalVM. The immediate goals are:

- Whether it can be faster than Java code (compile time + execution time) created based on the query execution plan
  - on Standard JVM
  - on GraalVM

**Comment by 0x00-qa** [comment]
Thank you for your reply. I'm researching calcite and arrow recently. I'm looking forward to your results.
